runtime: python
env: flex
entrypoint: gunicorn -b :$PORT server:application

runtime_config:
  python_version: 2

resources:
  cpu: 2
  memory_gb: 4.0

env_variables:
  VOCAB_SIZE: 25000
  DATA_DIR: gs://youmachine-174420-ubot-dev/data
  TRAIN_DIR: gs://youmachine-174420-ubot-dev/training
  LOG_DIR: gs://youmachine-174420-ubot-dev/logs
